[package]
name = "server"
version = "0.1.0"
authors = ["Sean Stangl <sean.stangl@gmail.com>"]

[dependencies]
diesel = { version = "0.99.0", features = ["sqlite", "huge-tables"] }
diesel_infer_schema = { version = "0.99.0", features = ["sqlite"] }
r2d2-diesel = "0.99.0"
r2d2 = "0.8.1"
dotenv = "0.10.1"
serde = "1.0"
serde_derive = "1.0"

# See https://github.com/SergioBenitez/Rocket/issues/513
# This will also be fixed by 0.4.0.
[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
branch = "v0.3"

[dependencies.rocket_codegen]
git = "https://github.com/SergioBenitez/Rocket"
branch = "v0.3"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
branch = "v0.3"
features = ["handlebars_templates"]

[patch.crates-io]
ring = { git = "https://github.com/SergioBenitez/ring", branch = "v0.11" }
