[package]
name = "server"
version = "0.1.0"
authors = ["Sean Stangl <sean.stangl@gmail.com>"]

[dependencies]
diesel = { version = "0.99.0", features = ["sqlite", "huge-tables"] }
diesel_infer_schema = { version = "0.99.0", features = ["sqlite"] }
r2d2-diesel = "0.99.0"
r2d2 = "0.8.1"
dotenv = "0.10.1"
rocket = "0.3.5"
rocket_codegen = "0.3.5"
rocket_contrib = { version = "0.3.5", features = ["handlebars_templates"] }
serde = "1.0"
serde_derive = "1.0"
